const specializations = [
    { name: 'Criminal Law', description: 'Focuses on crimes and punishments' },
    { name: 'Family Law', description: 'Deals with family-related issues' },
    { name: 'Corporate Law', description: 'Handles business and corporate matters' },
    { name: 'Immigration Law', description: 'Assists with immigration and naturalization' },
    { name: 'Intellectual Property Law', description: 'Protects intellectual property rights' },
    { name: 'Employment Law', description: 'Deals with employment-related issues' },
    { name: 'Personal Injury Law', description: 'Handles cases involving personal injury' },
    { name: 'Real Estate Law', description: 'Focuses on property and real estate transactions' },
    { name: 'Tax Law', description: 'Specializes in tax-related matters' },
    { name: 'Environmental Law', description: 'Deals with environmental protection and regulations' },
    { name: 'Bankruptcy Law', description: 'Assists with bankruptcy and financial restructuring' },
    { name: 'Civil Rights Law', description: 'Focuses on the protection of individual civil rights' },
    { name: 'Construction Law', description: 'Deals with construction-related legal issues' },
    { name: 'Consumer Protection Law', description: 'Protects consumers from fraudulent and unfair business practices' },
    { name: 'Contract Law', description: 'Handles the negotiation and enforcement of contracts' },
    { name: 'Education Law', description: 'Focuses on issues related to schools and education' },
    { name: 'Elder Law', description: 'Addresses legal issues affecting the elderly' },
    { name: 'Entertainment Law', description: 'Deals with legal matters in the entertainment industry' },
    { name: 'Health Care Law', description: 'Handles legal issues in the health care sector' },
    { name: 'Insurance Law', description: 'Focuses on insurance policies and claims' },
    { name: 'International Law', description: 'Deals with laws governing international relations' },
    { name: 'Labor Law', description: 'Focuses on legal issues between employers and employees' },
    { name: 'Maritime Law', description: 'Handles legal issues related to maritime activities' },
    { name: 'Medical Malpractice Law', description: 'Deals with professional negligence by health care providers' },
    { name: 'Military Law', description: 'Focuses on laws governing the armed forces' },
    { name: 'Municipal Law', description: 'Deals with legal issues related to local government' },
    { name: 'Nursing Home Abuse Law', description: 'Addresses abuse and neglect in nursing homes' },
    { name: 'Patent Law', description: 'Protects inventions and intellectual property' },
    { name: 'Privacy Law', description: 'Focuses on data protection and privacy issues' },
    { name: 'Probate Law', description: 'Deals with the administration of estates' },
    { name: 'Product Liability Law', description: 'Handles cases involving defective products' },
    { name: 'Securities Law', description: 'Regulates the trade of securities and financial instruments' },
    { name: 'Social Security Disability Law', description: 'Assists with social security disability claims' },
    { name: 'Sports Law', description: 'Focuses on legal issues in the sports industry' },
    { name: 'Telecommunications Law', description: 'Deals with legal issues in the telecommunications sector' },
    { name: 'Trademark Law', description: 'Protects brand names and logos' },
    { name: 'Transportation Law', description: 'Handles legal issues related to transportation and logistics' },
    { name: 'Trusts and Estates Law', description: 'Focuses on the management and distribution of estates' },
    { name: 'Veterans Law', description: 'Assists veterans with legal issues' },
    { name: 'Workers Compensation Law', description: 'Deals with compensation claims for workplace injuries' },
    { name: 'Cybersecurity Law', description: 'Focuses on legal issues related to cybersecurity and data breaches' },
    { name: 'Aviation Law', description: 'Handles legal issues related to air travel and aircraft' },
    { name: 'Agricultural Law', description: 'Deals with laws related to agriculture and farming' },
    { name: 'Antitrust Law', description: 'Regulates competition and prevents monopolies' },
    { name: 'Banking Law', description: 'Focuses on legal issues related to banks and financial institutions' },
    { name: 'Energy Law', description: 'Deals with legal issues in the energy sector' },
    { name: 'Gaming Law', description: 'Focuses on legal issues related to gambling and casinos' },
    { name: 'Franchise Law', description: 'Handles legal matters related to franchising businesses' },
    { name: 'Foreclosure Law', description: 'Deals with the process of foreclosing on properties' },
    { name: 'Child Custody Law', description: 'Focuses on legal issues related to child custody' },
    { name: 'Juvenile Law', description: 'Handles legal matters involving minors' },
    { name: 'Domestic Violence Law', description: 'Deals with cases of domestic abuse and violence' },
    { name: 'Asylum Law', description: 'Assists with legal matters related to asylum seekers' },
    { name: 'Land Use Law', description: 'Focuses on regulations related to the use of land' },
    { name: 'Eminent Domain Law', description: 'Handles cases involving government acquisition of private property' },
    { name: 'Zoning Law', description: 'Deals with the regulation of land use and development' },
    { name: 'Hospitality Law', description: 'Focuses on legal issues in the hospitality industry' },
    { name: 'Internet Law', description: 'Deals with legal issues related to the internet and online activities' },
    { name: 'Media Law', description: 'Handles legal matters in the media industry' },
    { name: 'Food and Drug Law', description: 'Regulates the safety and efficacy of food and pharmaceuticals' },
    { name: 'Mining Law', description: 'Deals with legal issues in the mining industry' },
    { name: 'Public Interest Law', description: 'Focuses on legal issues affecting the public good' },
    { name: 'Lobbying Law', description: 'Regulates the activities of lobbyists and lobbying firms' },
    { name: 'Civil Litigation', description: 'Handles disputes between individuals or organizations' },
    { name: 'Class Action Law', description: 'Deals with lawsuits involving a large group of people' },
    { name: 'Alternative Dispute Resolution', description: 'Focuses on resolving disputes outside of court' },
  ];
  

  const sampleLawyers = [
    {
      email: 'lawyer29@example.com',
      fullNames: 'Kakembo Charles',
      phoneNumber: '1234567890',
      location: 'Kampala, Uganda',
      avatar: 'https://randomuser.me/api/portraits/men/1.jpg',
      password: 'password@123',
      role: 'lawyer',
      about: 'With over a decade of experience in corporate law, I specialize in guiding businesses through complex legal landscapes. My expertise spans mergers, acquisitions, and contractual negotiations, ensuring compliance and strategic growth. Committed to delivering practical solutions that protect your business interests.',
      appointments: [],
      reviewsReceived: [],
      reviewsGiven: [],
      isEmailVerified: true,
      isPhoneNumberVerified: true,
      isProfilePublic: true,
      isVerified: true,
      availableForWork: true,
      yearsOfExperience: 10,
      specializations: [],
      completedConsultations: 0,
      availableSlots: [
        { day: 'Monday', timeSlots: [{ startTime: '9:00 AM', endTime: '10:00 AM' }] },
        { day: 'Tuesday', timeSlots: [{ startTime: '10:00 AM', endTime: '11:00 AM' }] },
      ],
      employmentHistory: [
        {
          companyName: 'Law Firm XYZ',
          jobTitle: 'Senior Associate',
          description: 'Handled complex corporate litigation cases.',
          startMonth: 'January',
          startYear: 2010,
          endMonth: 'December',
          endYear: 2020,
          isCurrent: false,
        },
      ],
      education: [
        {
          institutionName: 'Law School ABC',
          degree: 'Juris Doctor',
          fieldOfStudy: 'Law',
          startYear: 2006,
          endYear: 2009,
          currentlyAttending: false,
        },
      ],
      socialMediaLinkedAccounts: [{ platform: 'LinkedIn', url: 'https://linkedin.com/lawyer1' }],
      averageRating: 0,
      numOfReviews: 0,
    },
    {
      email: 'lawyer30@example.com',
      fullNames: 'Sarah Johnson',
      phoneNumber: '0987654321',
      location: 'Nairobi, Kenya',
      avatar: 'https://randomuser.me/api/portraits/women/1.jpg',
      password: 'password@123',
      role: 'lawyer',
      about: 'Experienced in family law, I provide compassionate and effective representation for clients facing divorce, child custody disputes, and other family-related matters. My goal is to achieve the best possible outcomes while minimizing stress for my clients.',
      appointments: [],
      reviewsReceived: [],
      reviewsGiven: [],
      isEmailVerified: true,
      isPhoneNumberVerified: true,
      isProfilePublic: true,
      isVerified: true,
      availableForWork: true,
      yearsOfExperience: 8,
      specializations: [],
      completedConsultations: 0,
      availableSlots: [
        { day: 'Wednesday', timeSlots: [{ startTime: '11:00 AM', endTime: '1:00 PM' }] },
        { day: 'Thursday', timeSlots: [{ startTime: '2:00 PM', endTime: '3:00 PM' }] },
      ],
      employmentHistory: [
        {
          companyName: 'Family Law Associates',
          jobTitle: 'Partner',
          description: 'Specialized in family law and mediation.',
          startMonth: 'February',
          startYear: 2012,
          endMonth: 'June',
          endYear: 2021,
          isCurrent: false,
        },
      ],
      education: [
        {
          institutionName: 'University of Nairobi',
          degree: 'LL.B',
          fieldOfStudy: 'Law',
          startYear: 2005,
          endYear: 2009,
          currentlyAttending: false,
        },
      ],
      socialMediaLinkedAccounts: [{ platform: 'LinkedIn', url: 'https://linkedin.com/lawyer2' }],
      averageRating: 0,
      numOfReviews: 0,
    },
    {
      email: 'lawyer31@example.com',
      fullNames: 'David Kimani',
      phoneNumber: '1122334455',
      location: 'Dar es Salaam, Tanzania',
      avatar: 'https://randomuser.me/api/portraits/men/2.jpg',
      password: 'password@123',
      role: 'lawyer',
      about: 'A specialist in criminal defense, I have successfully defended clients in a wide range of cases from minor offenses to serious felonies. My approach is thorough, strategic, and committed to upholding the rights of my clients.',
      appointments: [],
      reviewsReceived: [],
      reviewsGiven: [],
      isEmailVerified: true,
      isPhoneNumberVerified: true,
      isProfilePublic: true,
      isVerified: true,
      availableForWork: true,
      yearsOfExperience: 12,
      specializations: [],
      completedConsultations: 0,
      availableSlots: [
        { day: 'Friday', timeSlots: [{ startTime: '1:00 PM', endTime: '4:00 PM' }] },
        { day: 'Saturday', timeSlots: [{ startTime: '9:00 AM', endTime: '11:00 AM' }] },
      ],
      employmentHistory: [
        {
          companyName: 'Criminal Defense Experts',
          jobTitle: 'Lead Attorney',
          description: 'Led defense teams in high-profile cases.',
          startMonth: 'March',
          startYear: 2008,
          endMonth: 'Present',
          isCurrent: true,
        },
      ],
      education: [
        {
          institutionName: 'Dar es Salaam University',
          degree: 'LL.M',
          fieldOfStudy: 'Criminal Law',
          startYear: 2004,
          endYear: 2007,
          currentlyAttending: false,
        },
      ],
      socialMediaLinkedAccounts: [{ platform: 'LinkedIn', url: 'https://linkedin.com/lawyer3' }],
      averageRating: 0,
      numOfReviews: 0,
    },
    {
      email: 'lawyer32@example.com',
      fullNames: 'Amina Mohammed',
      phoneNumber: '6677889900',
      location: 'Lagos, Nigeria',
      avatar: 'https://randomuser.me/api/portraits/women/2.jpg',
      password: 'password@123',
      role: 'lawyer',
      about: 'Passionate about human rights law, I advocate for the marginalized and voiceless. My work involves both litigation and policy advocacy, striving to create a fairer society for all.',
      appointments: [],
      reviewsReceived: [],
      reviewsGiven: [],
      isEmailVerified: true,
      isPhoneNumberVerified: true,
      isProfilePublic: true,
      isVerified: true,
      availableForWork: true,
      yearsOfExperience: 15,
      specializations: [],
      completedConsultations: 0,
      availableSlots: [
        { day: 'Monday', timeSlots: [{ startTime: '10:00 AM', endTime: '12:00 PM' }] },
        { day: 'Thursday', timeSlots: [{ startTime: '3:00 PM', endTime: '5:00 PM' }] },
      ],
      employmentHistory: [
        {
          companyName: 'Human Rights Advocacy Group',
          jobTitle: 'Director',
          description: 'Led numerous campaigns and cases for human rights.',
          startMonth: 'April',
          startYear: 2005,
          endMonth: 'Present',
          isCurrent: true,
        },
      ],
      education: [
        {
          institutionName: 'University of Lagos',
          degree: 'LL.M',
          fieldOfStudy: 'Human Rights Law',
          startYear: 2000,
          endYear: 2003,
          currentlyAttending: false,
        },
      ],
      socialMediaLinkedAccounts: [{ platform: 'LinkedIn', url: 'https://linkedin.com/lawyer4' }],
      averageRating: 0,
      numOfReviews: 0,
    },
    {
      email: 'lawyer33@example.com',
      fullNames: 'John Doe',
      phoneNumber: '2233445566',
      location: 'Accra, Ghana',
      avatar: 'https://randomuser.me/api/portraits/men/3.jpg',
      password: 'password@123',
      role: 'lawyer',
      about: 'As a real estate lawyer, I provide comprehensive legal services for property transactions, ensuring compliance with all legal requirements and protecting clients\' interests. My experience includes residential and commercial property deals.',
      appointments: [],
      reviewsReceived: [],
      reviewsGiven: [],
      isEmailVerified: true,
      isPhoneNumberVerified: true,
      isProfilePublic: true,
      isVerified: true,
      availableForWork: true,
      yearsOfExperience: 7,
      specializations: [],
      completedConsultations: 0,
      availableSlots: [
        { day: 'Wednesday', timeSlots: [{ startTime: '9:00 AM', endTime: '10:00 AM' }] },
        { day: 'Friday', timeSlots: [{ startTime: '2:00 PM', endTime: '4:00 PM' }] },
      ],
      employmentHistory: [
        {
          companyName: 'Real Estate Legal Solutions',
          jobTitle: 'Attorney',
          description: 'Managed legal aspects of property transactions.',
          startMonth: 'June',
          startYear: 2014,
          endMonth: 'Present',
          isCurrent: true,
        },
      ],
      education: [
        {
          institutionName: 'University of Ghana',
          degree: 'LL.B',
          fieldOfStudy: 'Law',
          startYear: 2008,
          endYear: 2012,
          currentlyAttending: false,
        },
      ],
      socialMediaLinkedAccounts: [{ platform: 'LinkedIn', url: 'https://linkedin.com/lawyer5' }],
      averageRating: 0,
      numOfReviews: 0,
    },
  ];
  



  module.exports = {
    specializations, 
    sampleLawyers,
  }